r2c.bandit:
  violations:
    1062d649612b2a6f2873bfff0e7c7067:
      check_id: B602
      message: subprocess call with shell=True identified, security issue.
      path: bento/extra/hadolint.py
      severity: 2
      syntactic_context: "                 f\"docker run --network none --rm -i {self.DOCKER_IMAGE}\
        \ hadolint --format json - < {file}\",\n                 shell=True,\n   \
        \              cwd=self.base_path,\n                 encoding=\"utf8\",\n\
        \                 stdout=subprocess.PIPE,\n                 stderr=subprocess.PIPE,"
      tool_id: r2c.bandit
    5f54c7b612ae91017088f36ea409faa5:
      check_id: B602
      message: subprocess call with shell=True identified, security issue.
      path: tests/extra/test_python_tool.py
      severity: 2
      syntactic_context: "     proc = subprocess.Popen(\n         cmd, shell=True,\
        \ stdout=subprocess.PIPE, stderr=subprocess.PIPE, encoding=\"utf8\""
      tool_id: r2c.bandit
    8cb303211d02994d804e5ddc995ccc38:
      check_id: B602
      message: subprocess call with shell=True identified, security issue.
      path: tests/extra/test_python_tool.py
      severity: 2
      syntactic_context: "     proc = subprocess.Popen(\n         cmd, env=env, shell=True,\
        \ stdout=subprocess.PIPE, encoding=\"utf8\""
      tool_id: r2c.bandit
    a2c4503e8a1358b4e417754b97c28048:
      check_id: B602
      message: subprocess call with shell=True identified, security issue.
      path: tests/extra/test_python_tool.py
      severity: 2
      syntactic_context: "         env=env,\n         shell=True,\n         stdout=subprocess.PIPE,\n\
        \         stderr=subprocess.PIPE,\n         encoding=\"utf8\","
      tool_id: r2c.bandit
    a75a4820e9cfb8fe9324dc0f1671bbc8:
      check_id: B602
      message: subprocess call with shell=True identified, security issue.
      path: bento/extra/python_tool.py
      severity: 2
      syntactic_context: "             wrapped,\n             shell=True,\n      \
        \       cwd=str(self.base_path),\n             encoding=\"utf8\",\n      \
        \       executable=\"/bin/bash\",\n             env=env,\n             stdout=subprocess.PIPE,\n\
        \             stderr=subprocess.PIPE,"
      tool_id: r2c.bandit
    c6b42c4f58df6ae2e1d6a0dc31c8a355:
      check_id: B602
      message: subprocess call with shell=True identified, security issue.
      path: tests/extra/test_python_tool.py
      severity: 2
      syntactic_context: '     proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE,
        encoding="utf8")'
      tool_id: r2c.bandit
r2c.eslint:
  violations:
    c6e0f687a580ef5e681dc3b4a7ed7fce:
      check_id: no-undef
      message: '''x'' is not defined.'
      path: tests/acceptance/bad.js
      severity: 2
      syntactic_context: x = "potato";
      tool_id: r2c.eslint
r2c.flake8:
  violations:
    b0f635f6ec3c1ea48b57915726c320c2:
      check_id: F841
      message: local variable 'expected_returncode' is assigned to but never used
      path: tests/acceptance/qa.py
      severity: 2
      syntactic_context: '    expected_returncode = step.get("returncode")'
      tool_id: r2c.flake8
r2c.requests:
  violations: {}
